# Travis CI Configuration
language: ruby
rvm:
  - 2.2.3
services:
  - postgresql
before_script:
  - psql -c 'create database JFchess_test;' -U postgres
  - cp config/database.yml.travis config/database.yml