# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3146d3be201ab55775fbf22b72b971a7d583ceeb73b4348553d2fa43d1f20ff295b7a38ae7d9b00622ab9a544dd5c43e4319b8e4df7a75bcefd270db2c093e96

test:
  secret_key_base: ed54f64eb80c094fdd513ef29b8d6e9964980bc5e68fae4faf42b6e5bfb88ec607a2fc3524f040c305b4c071fecbea0ca927527d9ce96c7f53c6e3969702cd98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
